In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
  
%matplotlib inline

#### Loading the dataset

In [24]:

df = pd.read_excel('Covid-19 vaccinations-by-manufacturer-Efficacy included- DSE2700.xlsx',skiprows=1,sheet_name='vaccinations-by-manufacturer-up')

In [25]:
df.head()

,Country,Date,Vaccine_Manufacturer,Total_Vaccinations,Severe Disease,Infection,Severe Disease.1,Infection.1,Severe Disease.2,Infection.2,Severe Disease.3,Infection.3,Severe Disease.4,Infection.4,Severe Disease.5,Infection.5
0,Argentina,2020-12-29,Oxford/AstraZeneca,1,0.94,0.63,0.94,0.63,0.94,0.69,0.94,0.69,0.94,0.69,0.71,0.36
1,Argentina,2020-12-29,Sinopharm/Beijing,1,0.73,0.68,0.73,0.68,0.71,0.67,0.71,0.67,0.71,0.67,0.53,0.35
2,Argentina,2020-12-29,Sputnik V,20488,18848.96,17619.68,18848.96,17619.68,18234.32,17414.80,18234.32,17414.80,18234.32,17414.80,11268.40,7375.68
3,Argentina,2020-12-30,Sputnik V,40590,37342.80,34907.40,37342.80,34907.40,36125.10,34501.50,36125.10,34501.50,36125.10,34501.50,22324.50,14612.40
4,Argentina,2020-12-31,Sputnik V,43396,39924.32,37320.56,39924.32,37320.56,38622.44,36886.60,38622.44,36886.60,38622.44,36886.60,23867.80,15622.56

#### Dropping the Ancestral,Gamma & Delta

In [26]:
df.drop(columns=['Severe Disease', 'Infection', 'Severe Disease.3', 'Infection.3',
       'Severe Disease.4', 'Infection.4'], inplace=True, axis=1)

#### Printing the columns names

In [27]:
df.columns

Index(['Country', 'Date', 'Vaccine_Manufacturer', 'Total_Vaccinations',
       'Severe Disease.1', 'Infection.1', 'Severe Disease.2', 'Infection.2',
       'Severe Disease.5', 'Infection.5'],
      dtype='object')

#### Renaming columns names

In [28]:
df.rename({'Severe Disease.1': 'alpha_severe', 'Infection.1': 'alpha_infection',
                'Severe Disease.2': 'beta_severe'  , 'Infection.2': 'beta_infection',
                'Severe Disease.5':'omicron_severe', 'Infection.5':'omicron_infection'}, axis=1, inplace=True)  # new method

#### Changing datatype of columns from float to Integers

In [29]:
#Change the data type of features
df.alpha_severe = df.alpha_severe.astype(int)
df.alpha_infection = df.alpha_infection.astype(int)
df.beta_severe = df.beta_severe.astype(int)
df.beta_infection = df.beta_infection.astype(int)
df.omicron_severe = df.omicron_severe.astype(int)
df.omicron_infection =df.omicron_infection.astype(int)

#### Dropping NA values if any exists

In [30]:
df.dropna(inplace=True)

In [31]:
df

,Country,Date,Vaccine_Manufacturer,Total_Vaccinations,alpha_severe,alpha_infection,beta_severe,beta_infection,omicron_severe,omicron_infection
0,Argentina,2020-12-29,Oxford/AstraZeneca,1,0,0,0,0,0,0
1,Argentina,2020-12-29,Sinopharm/Beijing,1,0,0,0,0,0,0
2,Argentina,2020-12-29,Sputnik V,20488,18848,17619,18234,17414,11268,7375
3,Argentina,2020-12-30,Sputnik V,40590,37342,34907,36125,34501,22324,14612
4,Argentina,2020-12-31,Sputnik V,43396,39924,37320,38622,36886,23867,15622
...,...,...,...,...,...,...,...,...,...,...
48145,European Union,2022-10-17,Pfizer/BioNTech,633735112,602048356,545012196,602048356,532337494,456289280,0
48146,European Union,2022-10-17,Sinopharm/Beijing,2317509,1691781,1575906,1645431,1552731,1228279,811128
48147,European Union,2022-10-17,Sinovac,6772,3386,3182,3318,3115,2505,1625
48148,European Union,2022-10-17,Sputnik V,1845376,1697745,1587023,1642384,1568569,1014956,664335
48149,European Union,2022-10-17,Valneva,2112,1584,1478,1541,1457,1161,760

In [33]:
df.to_csv("FinalCovidData.csv")